version: '3.7'
services:
  web:
    build: .
    ports:
      - "217.25.88.206:217.25.88.206"
  db:
    image: postgres
    ports:
      - "5432:5432"

    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef